### PR TITLE
Prevent compilation issues on OTP 24

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Opening as draft since I'll need to push to `mixer`, get that approved and then tagged, to later import here, since it's also suffering from `parse_transform` OTP-24 specific _issues_. Basically the same one I fixed in the `lager` version I imported here.

- [x] wait for https://github.com/inaka/mixer/pull/18 to be merged and tagged/released
- [x] wait for https://github.com/benoitc/hackney/pull/676 to be merged and tagged/released
- [x] wait for https://github.com/erlang-lager/lager/pull/539 to be merged and tagged/released (or rather replace `lager` with `logger`)

... then aim to close this pull request.

### CODE REVIEW

**Comment by elbrujohalcon** [comment]
https://hex.pm/packages/inaka_mixer/1.1.1

**Comment by paulo-ferraz-oliveira** [comment]
I updated the dependencies in the initial description.

**Comment by elbrujohalcon** [comment]
We can consider moving away from `lager` and into `logger` if that makes sense.

**Comment by paulo-ferraz-oliveira** [comment]
It makes sense to move to `logger`, but I'm guessing it's a bit more trouble than simply updating the calls.

**Comment by paulo-ferraz-oliveira** [comment]
Still waiting on `hackney`.
`lager` is hopefully fully OTP-24 ready (as much as `master` represents it) and waiting for merge+release.

**Comment by paulo-ferraz-oliveira** [comment]
[`lager` 3.9.1](https://github.com/erlang-lager/lager/releases/tag/3.9.1)'s out. We're only missing `hackney` \o/.

**Comment by paulo-ferraz-oliveira** [comment]
The `hackney` bump forces us to go to OTP 21, but I'm not sure that's bad :)

**Review by elbrujohalcon — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
Ready for merge when you are.

**Comment by paulo-ferraz-oliveira** [comment]
If possible, could you tag it and release+publish it? Thanks much.

**Comment by elbrujohalcon** [comment]
[Done](https://hex.pm/packages/egithub/0.7.0).

**Pull request merged**
